/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#3d4247",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#161c24",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#313030",
        "secondary-container": "#4a4949",
        "surface-variant": "#3c4045",
        "surface-container-low": "#1f2327",
        "on-error": "#690005",
        "surface-container-lowest": "#14181b",
        "on-primary-container": "#00533c",
        "on-background": "#f0f1f5",
        "outline": "#85948c",
        "inverse-primary": "#006c4f",
        "error-container": "#93000a",
        "on-tertiary-container": "#434952",
        "primary-container": "#00d09c",
        "tertiary-container": "#b2b8c2",
        "surface-container": "#24282c",
        "inverse-surface": "#e1e2e7",
        "on-surface-variant": "#c5d2ca",
        "secondary": "#c8c6c5",
        "primary-fixed-dim": "#2fe0aa",
        "surface-tint": "#2fe0aa",
        "primary": "#44edb7",
        "surface-dim": "#171b1f",
        "tertiary-fixed-dim": "#c1c7d1",
        "on-tertiary-fixed-variant": "#414750",
        "on-secondary-container": "#bab8b7",
        "surface-container-high": "#2e3237",
        "surface-container-highest": "#3a3e43",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "surface": "#171b1f",
        "outline-variant": "#485650",
        "tertiary-fixed": "#dde3ee",
        "tertiary": "#ced3de",
        "inverse-on-surface": "#2e3134",
        "background": "#171b1f",
        "on-secondary-fixed-variant": "#474646",
        "on-primary-fixed": "#002116",
        "on-primary-fixed-variant": "#00513b",
        "on-tertiary": "#2b3139",
        "on-surface": "#f0f1f5",
        "on-primary": "#003828",
        "primary-fixed": "#59fdc5"
      },
      fontFamily: {
        "headline-lg": ["Manrope"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Manrope"],
        "label-sm": ["Inter"],
        "headline-sm": ["Manrope"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Manrope"]
      }
    }
  },
  plugins: [],
}
