import json
from query_engine import query_rag_engine

queries = [
    "What is the expense ratio of Nippon India Large Cap Fund?",
    "What are the exit load details for Nippon India Flexi Cap Fund?",
    "How can I download my capital gains statement?",
    "Who is the fund manager for the Nippon India Silver ETF FoF?",
    "What is the benchmark index for the Small Cap Fund?",
    "My PAN is BKDPD8829C. Show my details.",
    "Should I invest in Nippon India Large Cap?",
    "What returns has Nippon India Flexi Cap given in the last 1 year?"
]

output_md = "# Sample Q&A Log\n\nThis document provides representative test queries and responses generated by Groww Genie.\n\n"

for q in queries:
    res = query_rag_engine(q)
    output_md += f"### User Query\n> **{q}**\n\n"
    output_md += f"### Groww Genie Response\n{res['answer']}\n\n"
    if res.get('citation') and not res.get('is_refusal'):
        output_md += f"**Source:** [{res.get('citation_title', 'Factsheet')}]({res['citation']}) *(Last updated: {res['last_updated']})*\n\n"
    output_md += "---\n\n"

with open("docs/sample_qa.md", "w", encoding="utf-8") as f:
    f.write(output_md)

print("Generated sample_qa.md successfully.")
